Repository luketainton/FHeD, pull requests merged in 2020-08, with the labels that each got.

#87 Feature/71
  .github/issue-branch.yml
  README.md
Labels: type/docs

#92 :chart_with_upwards_trend: Add mailing list subscription button
  app/includes/footer.php
Labels: type/feature

#94 🚨 Testing New Existing Page
  .github/issue-branch.yml
  app/public/newexisting.php
Labels: type/epic, type/feature

#97 :bug: Subscribe link works now
  app/includes/footer.php
Labels: type/bug

#98 ✨ New Existing Launch
  app/public/existing.php
  app/public/newexisting.php
Labels: type/feature

#101 :sparkles: Move mailing list to Google Groups
  app/includes/footer.php
Labels: type/feature

#103 :construction: Update deploy script to automate versioning
  .github/workflows/deploy.yml
Labels: minor, type/bug

#104 Fixing YAML Issue
  .github/workflows/deploy.yml
Labels: minor, type/bug

#105 Fixing Fixing YAML
  .github/workflows/deploy.yml
Labels: minor

#106 Fixing Fixing Fixing Deploy
  .github/workflows/deploy.yml
Labels: minor, type/bug

#107 Fixing Fixing Fixing Fixing Deploy
  .github/workflows/deploy.yml
Labels: minor, type/bug

#108 Forgotten Bump
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/issue-branch.yml
  .github/workflows/autobranch.yml
  .github/workflows/deploy.yml
  .github/workflows/stale.yml
Labels: release:minor, type:bug

#110 Fix auto deployment and versioning
  .github/workflows/deploy.yml
Labels: release:patch, type:bug

#112 :bug: Remove 'env' sections
  .github/workflows/deploy.yml
Labels: release:patch, type:bug

#113 :bug: Make it plural!
  .github/workflows/deploy.yml
Labels: release:patch, type:bug

#114 :wrench: Push release version to Docker image
  Dockerfile
  app/includes/app_functions.php
  app/includes/footer.php
Labels: release:patch, type:bug

#118 :bug: User not added to DB - force die() on error
  app/includes/app_functions.php
  app/public/actions/login.php
Labels: release:patch, type:bug

#120 Fixing Login Die
  app/public/actions/login.php
Labels: release:patch, type:bug

#121 Broken login
  app/includes/footer.php
  app/public/actions/login.php
Labels: release:patch, type:bug

#122 Broken login
  app/includes/app_functions.php
  app/includes/footer.php
Labels: release:patch, type:bug

#124 Move break rule in footer
  app/includes/footer.php
Labels: release:patch, type:bug

#127 :sparkles: Add Sentry
  app/.env.sample
  app/composer.json
  app/composer.lock
  app/includes/app_functions.php
  app/includes/prereqs.php
Labels: release:minor, type:bug

#129 :construction: Migrate from Sentry to GlitchTip
  app/includes/prereqs.php
Labels: release:patch, type:bug

#132 🐛 Move opening and closing 'main' tags
  app/includes/footer.php
  app/includes/header.php
  app/public/index.php
Labels: release:patch, type:bug
